@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 业务系统 as user
participant 订单系统 as order
participant 支付核心 as core
participant 渠道系统 as channel

user -> order: 发起分账

activate order
order -> order: 查询支付单
order -> order: 查合并分账回退表
alt 普通退分账check流程
order -> order: 业务规则校验
end
order -> order: 落库 分账回退联系单和分账合并单
order -> core: 构建参数 申请退分账
core -> core: 插入回退分账单，记账
core -> channel: 请求渠道退分账
activate channel
channel -> core: 返回退分账结果
deactivate channel
core  -> order: 返回结果
order -> user: 结束
deactivate order


@enduml